
REACT_APP_GQL_ENDPOINT=$GQL_ENDPOINT \
REACT_APP_OIDC_AUTHORITY=$OIDC_AUTHORITY \
REACT_APP_OIDC_CLIENT_ID=$OIDC_CLIENT_ID \
REACT_APP_OIDC_SCOPE=$OIDC_SCOPE \
REACT_APP_OIDC_REDIRECT_URI=$OIDC_REDIRECT_URI \
REACT_APP_OIDC_SILENT_REDIRECT_URI=$OIDC_SILENT_REDIRECT_URI \
REACT_APP_OIDC_POST_LOGOUT_REDIRECT_URI=$OIDC_POST_LOGOUT_REDIRECT_URI \
yarn build

yarn global add serve
serve -s build
